=== poliana-dev/atividades-pos-2024/atividade03/quiz.dtd
<!ELEMENT quiz (disciplina, professor, turma, data, questoes)>
<!ATTLIST quiz versao CDATA #REQUIRED>

<!ELEMENT disciplina (#PCDATA)>

<!ELEMENT professor (nome, matricula?)>
    <!ELEMENT nome (#PCDATA)>
    <!ELEMENT matricula (#PCDATA)>

<!ELEMENT turma (#PCDATA)>
<!ELEMENT data (#PCDATA)>

<!ELEMENT questoes (questao+)>
    <!ELEMENT questao (enunciado, pontuacao, alternativas)>
            <!ELEMENT enunciado (#PCDATA)>
            <!ELEMENT pontuacao (#PCDATA)>
            <!ELEMENT alternativas (alternativa+)>
                <!ELEMENT alternativa (#PCDATA)>
                <!ATTLIST alternativa correta (sim|nao) #REQUIRED>

=== poliana-dev/atividades-pos-2024/atividade03/quiz.xml
<?xml version='1.0' encoding="utf-8"?>
<!DOCTYPE quiz SYSTEM "quiz.dtd">

<quiz versao="01">
    <disciplina>POS</disciplina>
    <professor>
        <nome>Cirilo</nome>
        <matricula>23243</matricula>
    </professor>
    <turma>Info web 4v</turma>

    <data>17/07/2024</data>

    <questoes>
        <questao>
            <enunciado>marque a alternativa correta sobre o git</enunciado>
            <pontuacao>5</pontuacao>
            <alternativas>
                <alternativa correta="nao"></alternativa>
                <alternativa correta="nao"></alternativa>
                <alternativa correta="nao"></alternativa>
                <alternativa correta="sim"></alternativa>
            </alternativas>
        </questao>

        <questao>
            <enunciado>explique diferen√ßas entre git e github</enunciado>
            <pontuacao>5</pontuacao>
            <alternativas>
                <alternativa correta="nao"></alternativa>
                <alternativa correta="sim"></alternativa>
                <alternativa correta="nao"></alternativa>
                <alternativa correta="nao"></alternativa>
            </alternativas>
        </questao>

        <questao>
            <enunciado>verdadeiro ou falso sobre xml</enunciado>
            <pontuacao>5</pontuacao>
            <alternativas>
                <alternativa correta="nao"></alternativa>
                <alternativa correta="sim"></alternativa>
                <alternativa correta="sim"></alternativa>
                <alternativa correta="nao"></alternativa>
            </alternativas>
        </questao>

        <questao>
            <enunciado>quais desses comandos em git esta correto?</enunciado>
            <pontuacao>5</pontuacao>
            <alternativas>
                <alternativa correta="nao"></alternativa>
                <alternativa correta="sim"></alternativa>
                <alternativa correta="nao"></alternativa>
                <alternativa correta="nao"></alternativa>
            </alternativas>
        </questao>

        <questao>
            <enunciado>marque a alternativa incorreta sobre os problemas que o gir resolve</enunciado>
            <pontuacao>5</pontuacao>
            <alternativas>
                <alternativa correta="nao"></alternativa>
                <alternativa correta="nao"></alternativa>
                <alternativa correta="sim"></alternativa>
                <alternativa correta="nao"></alternativa>
            </alternativas>
        </questao>
    </questoes>
</quiz>
